[package]
name = "lorenz"
version = "0.1.0"
edition = "2021"
default-run = "visualizer"

[dependencies]
idek = { git = "https://github.com/Masterchef365/idek.git", rev = "4c70d90" }
anyhow = "1"
ultraviolet = "0.9.0"
wav = "1"
structopt = { version = "0.3", default-features = false }
